name: vim/neovim
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
        neovim: [true]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Clone themis.vim
        uses: actions/checkout@v2
        with:
          repository: thinca/vim-themis
          path: .vim-themis
      - name: Clone vim-sexp
        uses: actions/checkout@v2
        with:
          repository: guns/vim-sexp
          path: .vim-sexp
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: nightly
          neovim: ${{ matrix.neovim }}
      - run: echo "./bin" >> $GITHUB_PATH
      - name: Install cljstyle
        run: ../installer/cljstyle.sh
        working-directory: ./bin
      - name: Install jet
        run: ../installer/jet.sh
        working-directory: ./bin
      - name: Install clj-kondo
        run: ../installer/clj-kondo.sh
        working-directory: ./bin
      - name: Run themis
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: ./.vim-themis/bin/themis
